# Generated by Django 5.2 on 2026-06-14 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0021_alter_course_total_lessons'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='lesson_weekday_pattern',
        ),
        migrations.AddField(
            model_name='course',
            name='is_fri',
            field=models.BooleanField(default=False, verbose_name='星期五'),
        ),
        migrations.AddField(
            model_name='course',
            name='is_mon',
            field=models.BooleanField(default=False, verbose_name='星期一'),
        ),
        migrations.AddField(
            model_name='course',
            name='is_sat',
            field=models.BooleanField(default=False, verbose_name='星期六'),
        ),
        migrations.AddField(
            model_name='course',
            name='is_sun',
            field=models.BooleanField(default=False, verbose_name='星期日'),
        ),
        migrations.AddField(
            model_name='course',
            name='is_thu',
            field=models.BooleanField(default=False, verbose_name='星期四'),
        ),
        migrations.AddField(
            model_name='course',
            name='is_tue',
            field=models.BooleanField(default=False, verbose_name='星期二'),
        ),
        migrations.AddField(
            model_name='course',
            name='is_wed',
            field=models.BooleanField(default=False, verbose_name='星期三'),
        ),
    ]
