# Generated by Django 5.2 on 2026-06-14 15:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0022_remove_course_lesson_weekday_pattern_course_is_fri_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='sign_up_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='報名時間'),
        ),
    ]
