# Generated by Django 5.2 on 2026-06-16 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0023_alter_signup_sign_up_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursemaincategory',
            name='main_cat_code',
            field=models.CharField(blank=True, max_length=50, verbose_name='命名編號'),
        ),
        migrations.AddField(
            model_name='coursesubcategory',
            name='sub_cat_code',
            field=models.CharField(blank=True, max_length=50, verbose_name='命名編號'),
        ),
        migrations.AddField(
            model_name='signuprefund',
            name='refund_reason',
            field=models.CharField(blank=True, max_length=200, verbose_name='退款原因'),
        ),
    ]
