# Generated by Django 5.2 on 2026-06-16 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0024_coursemaincategory_main_cat_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signuprefund',
            name='sign_up',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.signup', verbose_name='報名紀錄'),
        ),
    ]
