# Generated by Django 5.2 on 2026-06-16 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0025_alter_signuprefund_sign_up'),
        ('students', '0009_student_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='courses.course', verbose_name='課程'),
        ),
        migrations.AlterField(
            model_name='signup',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='students.student', verbose_name='學生'),
        ),
    ]
