# Generated by Django 5.2 on 2026-06-16 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0027_alter_courseschedule_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseschedule',
            name='lesson_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='上課日期'),
        ),
    ]
