# Generated by Django 5.2 on 2026-06-16 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0028_courseschedule_lesson_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courseschedule',
            options={'ordering': ['course', 'lesson_date', 'start_time'], 'verbose_name': '課程排班表', 'verbose_name_plural': '課程排班表'},
        ),
        migrations.RemoveField(
            model_name='courseschedule',
            name='day_of_week',
        ),
    ]
